# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Adam McCombs
tagline:          'Cool things are afoot.'
description:      'Hi. I build cool things, play with atoms, and take pretty photos. This site is how I document those projects.'
url:              http://mccombs.us
baseurl:          /

author:
  name:           'Adam McCombs'
  url:            https://twitter.com/admanmccombs

paginate:         5

# Custom vars
version:          2.1.0

github:
repository:           https://github.com/AdamMcCombs/AdamMcCombs.github.io
